import i18n from "i18next";
import { initReactI18next } from "react-i18next";

export const supportedLocales = ["zh-HK", "zh-CN", "en"] as const;
export type AppLocale = typeof supportedLocales[number];

const resources = {
  "zh-HK": { translation: {
    brand: "Yi · 易",
    nav: { cast: "起一卦", history: "閱讀紀錄", help: "關於與說明", contact: "聯絡我們", settings: "設定", account: "帳戶", admin: "營運", skip: "跳到主要內容", home: "Yi 首頁", menu: "選單", more: "更多", primaryLabel: "主要導覽", mobileLabel: "流動導覽", moreLabel: "更多頁面與偏好", castShort: "起卦", historyShort: "紀錄", helpShort: "幫助", accountShort: "帳戶", settingsHint: "語言、字體與外觀", contactHint: "支援與意見" },
    hero: { eyebrow: "一場安靜、可重複的反思儀式", title: "先把問題，\n放在光裡。", body: "《易》是一扇窗，讓我們與宇宙的其他維度對話。", start: "開始起卦", caption: "卦象／形態／變化", imageAlt: "周文王在神聖星海間排列蓍草，推演連結多重維度的《易》卦" },
    features: { label: "核心功能", methodsTitle: "三種經過驗證的起卦方法", methodsBody: "三數、三錢與安全隨機三種方式，都依循固定而可覆核的規則。", interpretationTitle: "以《高島易斷》為本的 AI 解讀", interpretationBody: "以審核過的《高島易斷》內容為基礎，在你需要時，提供有出處、可理解的 AI 解讀。", chatTitle: "深入的後續對話", chatBody: "它記得你這次閱讀的來龍去脈，讓你可以繼續追問、慢慢想清楚。" },
    cast: {
      title: "你的問題", questionHint: "寫下一個具體、你可以好好反思的問題（最多 280 字）", noQuestion: "我暫時沒有具體問題", continue: "選擇起卦方法", methodTitle: "選擇方法", number: "三數起卦", numberBody: "輸入上卦、下卦與一個動爻位置。", coin: "三錢起卦", coinBody: "擲幣六次，每次三枚，由初爻開始記錄。", random: "安全隨機", randomBody: "由瀏覽器的加密隨機生成，提交前你可以先覆核。", upper: "上卦（1-8）", lower: "下卦（1-8）", changing: "動爻（1-6）", heads: "正", tails: "反", line: "第 {{n}} 爻", bottom: "初爻／最下", top: "上爻／最上", generate: "生成一組安全隨機卦", regenerate: "重新生成", review: "覆核卦爻", reviewTitle: "提交前覆核", bottomUp: "卦爻由下至上排列，動爻以橙色標示。", yin: "陰", yang: "陽", moving: "動", still: "靜", back: "返回修改", confirm: "確認並選擇掛金", invalid: "請填妥資料，並檢查起卦內容。", resume: "繼續目前起卦", exit: "離開起卦", stepCount: "第 {{current}}／{{total}} 步", progressLabel: "起卦進度", stepChanged: "已進入{{step}}", generated: "已生成一組安全隨機卦" },
    trigrams: { 1: "乾 · 天", 2: "兌 · 澤", 3: "離 · 火", 4: "震 · 雷", 5: "巽 · 風", 6: "坎 · 水", 7: "艮 · 山", 8: "坤 · 地" },
    methodGuide: {
      title: "這個方法怎麼運作？",
      number: { body: "頭兩個數字決定上卦與下卦，第三個數字決定動爻。", point1: "上卦與下卦輸入 1–8，輸入框下方會即時顯示對應的八卦。", point2: "動爻輸入 1–6，由初爻往上數；三數起卦固定只有一個動爻。" },
      coin: { body: "擲幣六次，每次成一爻，由初爻開始。", point1: "每次把三枚錢幣分別設為正面或反面；正面算 3，反面算 2。", point2: "總和 6 為動陰、7 為靜陽、8 為靜陰、9 為動陽。", point3: "一卦可能沒有動爻，也可能有多個動爻。" },
      random: { body: "瀏覽器會一次過安全隨機生成六爻，提交前仍由你覆核。", point1: "斷開的爻是陰、完整的爻是陽；白色代表靜爻，橙色代表動爻。", point2: "一卦可能沒有動爻，也可能有多個動爻；想換一卦，重新生成即可。", point3: "下方的承諾碼是隨機資料的加密摘要：它記錄這次生成，卻不會公開原始隨機資料。" },
    },
    contribution: { title: "隨喜掛金", body: "這是對數碼服務的一點心意，並非慈善捐款。選擇 HK$0 亦可完成；正數金額會經 Stripe 安全結帳，待 webhook 核實付款後才會顯示結果。", custom: "自訂金額（HK$1–888，整數）", proceed: "完成並查看結果", checkout: "前往 Stripe 結帳", pending: "正在確認付款…", cancelled: "結帳已取消，你可以重新再選。", unavailable: "Stripe 設定完成前，暫不接受正數掛金；HK$0 的閱讀依然完整可用。" },
    specialLine: { nine: "用九", six: "用六" },
    result: { waiting: "結果準備中", waitingBody: "我們只以 Stripe 的驗證通知為準；此頁會自動更新。", primary: "本卦", relating: "之卦", kingWenOrder: "文王卦序", movingLines: "動爻", none: "無動爻", facts: "可重現的事實", sourcePending: "來源目錄審核中", sourceBody: "目前只顯示不依賴解讀文本的卦象事實；待權利與三語審核完成後，才會開放來源解讀與相關的 AI 內容。", sourceReviewed: "已審核來源目錄", sourceReviewedBody: "這次閱讀附有固定摘錄，均已註明出處、權利狀態，並通過三語審核；只有在你另行同意後，才會傳給 AI。", reflection: "AI 反思", reflectionQuestions: "值得繼續思考", reflectionCautions: "閱讀提醒", askReflection: "要不要加入 AI 反思？", archive: "儲存這次閱讀", archived: "已儲存", again: "再起一卦", chat: "和這次閱讀對話", share: "建立匿名分享" },
    consent: { title: "傳送甚麼，由你決定", body: "AI 完全可選。每次使用前，你都可以明確選擇；高風險問題絕不會傳給模型。", agree: "我同意把已選取的資料傳給 DeepSeek，用來產生反思", facts: "我同意把這次閱讀的卦象事實傳給 DeepSeek", question: "包括我原本的問題", sources: "包括經審核的來源摘錄", submit: "產生反思", decline: "暫不使用 AI", fallback: "這次沒有使用 AI；確定性結果依然完整。" },
    auth: { eyebrow: "閱讀存檔／筆記／對話", or: "或", title: "你的閱讀空間", signIn: "登入", signUp: "建立帳戶", name: "稱呼", email: "電郵", password: "密碼（至少 10 字元）", confirmPassword: "再次輸入新密碼", submit: "繼續", google: "使用 Google", microsoft: "使用 Microsoft", verify: "如帳戶存在，請查收郵件並按連結繼續。", verified: "電郵已驗證。你現在可以登入。", invalidLink: "這個連結無效或已過期，請重新申請。", forgot: "忘記密碼？", reset: "傳送重設連結", newPasswordTitle: "設定新密碼", newPasswordBody: "輸入至少 10 字元的新密碼。", setPassword: "更新密碼", resetDone: "密碼已更新。請使用新密碼登入。", signOut: "登出", needAccount: "儲存、筆記、搜尋與對話需要帳戶。" },
    history: { eyebrow: "個人存檔", saved: "已儲存閱讀", searchLabel: "搜尋閱讀紀錄", title: "閱讀紀錄", empty: "還沒有儲存的閱讀。", emptyTitle: "從一次起卦開始", noMatches: "找不到符合條件的閱讀。", search: "搜尋問題、卦象、反思與筆記", notes: "筆記", addNote: "新增筆記", saveNote: "儲存筆記", noteSaved: "筆記已儲存", delete: "刪除", deleteReading: "刪除這次閱讀", deleteConfirm: "確定要永久刪除這次閱讀嗎？", open: "查看" },
    chat: { eyebrow: "持續保存／可繼續", title: "閱讀對話", intro: "對話會保留你起卦時的問題與卦象。每天最多 50 則提問。", placeholder: "寫下你想梳理的部分…", send: "傳送", reconnecting: "正在重新連線…", connected: "已連線", statusLabel: "連線狀態", empty: "從你最想梳理的一點開始。", you: "你", delete: "刪除對話", deleteConfirm: "確定永久刪除這段對話？" },
    share: { title: "匿名分享", anonymous: "匿名／七日", body: "連結只包含卦象事實，以及你選擇加入的反思；不會有身份、原問題、筆記或對話，並於七日後失效。", includeReflection: "加入 AI 反思", create: "建立七日連結", copy: "複製連結", native: "分享", image: "下載長圖與 QR Code", revoked: "分享已撤銷", expired: "分享不存在、已撤銷或已過期", url: "分享連結", imageTagline: "一份匿名分享的私人反思", expires: "有效至 {{date}}" },
    settings: { eyebrow: "個人化", title: "設定", locale: "語言", font: "字體大小", theme: "外觀", small: "小", medium: "中", large: "大", light: "淺色", dark: "深色", system: "跟隨系統", save: "儲存設定", export: "匯出我的資料", delete: "刪除帳戶", deleteBody: "我們會先寄一封確認郵件；完成確認後，帳戶與已儲存的資料將無法復原。" },
    help: { eyebrow: "關於／方法／私隱", title: "把卦象當作一面鏡子", body1: "Yi 會依你選擇的方法生成六爻，再按固定的文王卦序找出本卦與之卦；相同的輸入，永遠得到相同的結果。", body2: "它並非預言，也不是診斷、投資或法律建議；它適合用來把問題想清楚、覺察自己的假設，並設計下一個可逆的小步驟。", methods: "三種方法都依由下至上的爻序，並會在提交前請你覆核。", privacy: "分享永遠匿名；AI 的使用與資料範圍，每次都由你重新決定。", takashima: { eyebrow: "人物／易學傳承", title: "高島嘉右衛門", body: "高島嘉右衛門（1832–1914），號呑象，是幕末至明治時期的橫濱實業家與易斷家。他生於江戶三十間堀，幼名清三郎，後改名嘉兵衛，再改名嘉右衛門。", source: "閱讀日文維基百科條目" } },
    contact: { eyebrow: "支援／意見", title: "聯絡我們", subject: "主題", message: "訊息", send: "送出", received: "已收到。我們會按順序回覆。" },
    turnstile: { label: "機械人驗證", error: "安全驗證未能完成。請重新整理頁面，或改用沒有 VPN／代理的其他瀏覽器。" },
    admin: { eyebrow: "受限／內容已遮蔽", title: "營運控制台", summary: "總覽", users: "帳戶", readings: "閱讀元資料", contributions: "掛金與付款", ai: "AI 用量", config: "限額設定", noContent: "一般營運頁不顯示問題、筆記或對話內容。" },
    ops: { id: "識別碼", email: "電郵", role: "角色", status: "狀態", activate: "恢復", suspend: "停用", dashboard: "控制台", aiEnabled: "全域啟用 AI", tokens: "每日 token 上限", spend: "每日開支上限（美元微單位）", concurrency: "模型最高並行數", save: "儲存限額", saving: "儲存中…" },
    common: { loading: "載入中…", loadingTitle: "內容整理中", error: "操作未完成，請再試一次。", retry: "重試", close: "關閉", save: "儲存", cancel: "取消", optional: "選填", copyDone: "已複製", back: "返回" },
  } },
  "zh-CN": { translation: {
    brand: "Yi · 易",
    nav: { cast: "起一卦", history: "阅读记录", help: "关于与说明", contact: "联系我们", settings: "设置", account: "账户", admin: "运营", skip: "跳到主要内容", home: "Yi 首页", menu: "菜单", more: "更多", primaryLabel: "主要导航", mobileLabel: "移动导航", moreLabel: "更多页面与偏好", castShort: "起卦", historyShort: "记录", helpShort: "帮助", accountShort: "账户", settingsHint: "语言、字体与外观", contactHint: "支持与反馈" },
    hero: { eyebrow: "一场安静、可重复的反思仪式", title: "先把问题，\n放在光里。", body: "《易》是一扇窗，让我们与宇宙的其他维度对话。", start: "开始起卦", caption: "卦象／形态／变化", imageAlt: "周文王在神圣星海间排列蓍草，推演连接多重维度的《易》卦" },
    features: { label: "核心功能", methodsTitle: "三种经过验证的起卦方法", methodsBody: "三数、三钱与安全随机三种方式，都遵循固定而可复核的规则。", interpretationTitle: "以《高岛易断》为本的 AI 解读", interpretationBody: "以审核过的《高岛易断》内容为基础，在你需要时，提供有出处、可理解的 AI 解读。", chatTitle: "深入的后续对话", chatBody: "它记得你这次阅读的来龙去脉，让你可以继续追问、慢慢想清楚。" },
    cast: { title: "你的问题", questionHint: "写下一个具体、你可以好好反思的问题（最多 280 字）", noQuestion: "我暂时没有具体问题", continue: "选择起卦方法", methodTitle: "选择方法", number: "三数起卦", numberBody: "输入上卦、下卦与一个动爻位置。", coin: "三钱起卦", coinBody: "掷币六次，每次三枚，由初爻开始记录。", random: "安全随机", randomBody: "由浏览器的加密随机生成，提交前你可以先复核。", upper: "上卦（1-8）", lower: "下卦（1-8）", changing: "动爻（1-6）", heads: "正", tails: "反", line: "第 {{n}} 爻", bottom: "初爻／最下", top: "上爻／最上", generate: "生成一组安全随机卦", regenerate: "重新生成", review: "复核卦爻", reviewTitle: "提交前复核", bottomUp: "卦爻由下至上排列，动爻以橙色标示。", yin: "阴", yang: "阳", moving: "动", still: "静", back: "返回修改", confirm: "确认并选择随喜赞助", invalid: "请填妥资料，并检查起卦内容。", resume: "继续当前起卦", exit: "离开起卦", stepCount: "第 {{current}}／{{total}} 步", progressLabel: "起卦进度", stepChanged: "已进入{{step}}", generated: "已生成一组安全随机卦" },
    trigrams: { 1: "乾 · 天", 2: "兑 · 泽", 3: "离 · 火", 4: "震 · 雷", 5: "巽 · 风", 6: "坎 · 水", 7: "艮 · 山", 8: "坤 · 地" },
    methodGuide: {
      title: "这个方法怎么运作？",
      number: { body: "头两个数字决定上卦与下卦，第三个数字决定动爻。", point1: "上卦与下卦输入 1–8，输入框下方会即时显示对应的八卦。", point2: "动爻输入 1–6，由初爻往上数；三数起卦固定只有一个动爻。" },
      coin: { body: "掷币六次，每次成一爻，由初爻开始。", point1: "每次把三枚钱币分别设为正面或反面；正面算 3，反面算 2。", point2: "总和 6 为动阴、7 为静阳、8 为静阴、9 为动阳。", point3: "一卦可能没有动爻，也可能有多个动爻。" },
      random: { body: "浏览器会一次性安全随机生成六爻，提交前仍由你复核。", point1: "断开的爻是阴、完整的爻是阳；白色代表静爻，橙色代表动爻。", point2: "一卦可能没有动爻，也可能有多个动爻；想换一卦，重新生成即可。", point3: "下方的承诺码是随机数据的加密摘要：它记录这次生成，却不会公开原始随机数据。" },
    },
    contribution: { title: "随喜赞助", body: "这是对数字服务的一点心意，并非慈善捐款。选择 HK$0 亦可完成；正数金额会经 Stripe 安全结账，待 webhook 核实付款后才会显示结果。", custom: "自订金额（HK$1–888，整数）", proceed: "完成并查看结果", checkout: "前往 Stripe 结账", pending: "正在确认付款…", cancelled: "结账已取消，你可以重新再选。", unavailable: "Stripe 设置完成前，暂不接受正数赞助；HK$0 的阅读依然完整可用。" },
    specialLine: { nine: "用九", six: "用六" },
    result: { waiting: "结果准备中", waitingBody: "我们只以 Stripe 的验证通知为准；此页会自动更新。", primary: "本卦", relating: "之卦", kingWenOrder: "文王卦序", movingLines: "动爻", none: "无动爻", facts: "可重现的事实", sourcePending: "来源目录审核中", sourceBody: "目前只显示不依赖解读文本的卦象事实；待权利与三语审核完成后，才会开放来源解读与相关的 AI 内容。", sourceReviewed: "已审核来源目录", sourceReviewedBody: "这次阅读附有固定摘录，均已注明出处、权利状态，并通过三语审核；只有在你另行同意后，才会传给 AI。", reflection: "AI 反思", reflectionQuestions: "值得继续思考", reflectionCautions: "阅读提醒", askReflection: "要不要加入 AI 反思？", archive: "保存这次阅读", archived: "已保存", again: "再起一卦", chat: "和这次阅读对话", share: "创建匿名分享" },
    consent: { title: "发送什么，由你决定", body: "AI 完全可选。每次使用前，你都可以明确选择；高风险问题绝不会传给模型。", agree: "我同意把已选的数据传给 DeepSeek，用来生成反思", facts: "我同意把这次阅读的卦象事实传给 DeepSeek", question: "包括我原本的问题", sources: "包括经审核的来源摘录", submit: "生成反思", decline: "暂不使用 AI", fallback: "这次没有使用 AI；确定性结果依然完整。" },
    auth: { eyebrow: "阅读存档／笔记／对话", or: "或", title: "你的阅读空间", signIn: "登录", signUp: "创建账户", name: "称呼", email: "邮箱", password: "密码（至少 10 个字符）", confirmPassword: "再次输入新密码", submit: "继续", google: "使用 Google", microsoft: "使用 Microsoft", verify: "如账户存在，请查收邮件并点击链接继续。", verified: "邮箱已验证。你现在可以登录。", invalidLink: "此链接无效或已过期，请重新申请。", forgot: "忘记密码？", reset: "发送重置链接", newPasswordTitle: "设置新密码", newPasswordBody: "输入至少 10 个字符的新密码。", setPassword: "更新密码", resetDone: "密码已更新。请使用新密码登录。", signOut: "退出登录", needAccount: "保存、笔记、搜索与对话需要账户。" },
    history: { eyebrow: "个人存档", saved: "已保存阅读", searchLabel: "搜索阅读记录", title: "阅读记录", empty: "还没有保存的阅读。", emptyTitle: "从一次起卦开始", noMatches: "找不到符合条件的阅读。", search: "搜索问题、卦象、反思与笔记", notes: "笔记", addNote: "新增笔记", saveNote: "保存笔记", noteSaved: "笔记已保存", delete: "删除", deleteReading: "删除这次阅读", deleteConfirm: "确定要永久删除这次阅读吗？", open: "查看" },
    chat: { eyebrow: "持续保存／可继续", title: "阅读对话", intro: "对话会保留你起卦时的问题与卦象。每天最多 50 则提问。", placeholder: "写下你想梳理的部分…", send: "发送", reconnecting: "正在重新连接…", connected: "已连接", statusLabel: "连接状态", empty: "从你最想梳理的一点开始。", you: "你", delete: "删除对话", deleteConfirm: "确定永久删除这段对话？" },
    share: { title: "匿名分享", anonymous: "匿名／七天", body: "链接只包含卦象事实，以及你选择加入的反思；不会有身份、原问题、笔记或对话，并于七天后失效。", includeReflection: "加入 AI 反思", create: "创建七天链接", copy: "复制链接", native: "分享", image: "下载长图与二维码", revoked: "分享已撤销", expired: "分享不存在、已撤销或已过期", url: "分享链接", imageTagline: "一份匿名分享的私人反思", expires: "有效至 {{date}}" },
    settings: { eyebrow: "个性化", title: "设置", locale: "语言", font: "字体大小", theme: "外观", small: "小", medium: "中", large: "大", light: "浅色", dark: "深色", system: "跟随系统", save: "保存设置", export: "导出我的数据", delete: "删除账户", deleteBody: "我们会先寄一封确认邮件；完成确认后，账户与已保存的数据将无法恢复。" },
    help: { eyebrow: "关于／方法／隐私", title: "把卦象当作一面镜子", body1: "Yi 会按你选择的方法生成六爻，再按固定的文王卦序找出本卦与之卦；相同的输入，永远得到相同的结果。", body2: "它并非预言，也不是诊断、投资或法律建议；它适合用来把问题想清楚、察觉自己的假设，并设计下一个可逆的小步骤。", methods: "三种方法都依由下至上的爻序，并会在提交前请你复核。", privacy: "分享永远匿名；AI 的使用与数据范围，每次都由你重新决定。", takashima: { eyebrow: "人物／易学传承", title: "高岛嘉右卫门", body: "高岛嘉右卫门（1832–1914），号吞象，是幕末至明治时期的横滨实业家与易断家。他生于江户三十间堀，幼名清三郎，后改名嘉兵卫，再改名嘉右卫门。", source: "阅读日文维基百科条目" } },
    contact: { eyebrow: "支持／反馈", title: "联系我们", subject: "主题", message: "消息", send: "提交", received: "已收到。我们会按顺序回复。" },
    turnstile: { label: "机器人验证", error: "安全验证未能完成。请刷新页面，或改用没有 VPN／代理的其他浏览器。" },
    admin: { eyebrow: "受限／内容已隐藏", title: "运营控制台", summary: "总览", users: "账户", readings: "阅读元数据", contributions: "随喜赞助与付款", ai: "AI 用量", config: "限额设置", noContent: "一般运营页面不显示问题、笔记或对话内容。" },
    ops: { id: "标识符", email: "邮箱", role: "角色", status: "状态", activate: "恢复", suspend: "停用", dashboard: "控制台", aiEnabled: "全局启用 AI", tokens: "每日 token 上限", spend: "每日开支上限（美元微单位）", concurrency: "模型最高并发数", save: "保存限额", saving: "保存中…" },
    common: { loading: "加载中…", loadingTitle: "内容整理中", error: "操作未完成，请再试一次。", retry: "重试", close: "关闭", save: "保存", cancel: "取消", optional: "选填", copyDone: "已复制", back: "返回" },
  } },
  en: { translation: {
    brand: "Yi · 易",
    nav: { cast: "Cast", history: "History", help: "About & help", contact: "Contact", settings: "Settings", account: "Account", admin: "Operations", skip: "Skip to main content", home: "Yi home", menu: "Menu", more: "More", primaryLabel: "Primary navigation", mobileLabel: "Mobile navigation", moreLabel: "More pages and preferences", castShort: "Cast", historyShort: "History", helpShort: "Help", accountShort: "Account", settingsHint: "Language, text, and appearance", contactHint: "Support and feedback" },
    hero: { eyebrow: "A quiet, reproducible reflection ritual", title: "Place the question\nin the light.", body: "Yi is a tool for humans to communicate with other dimensions of the universe.", start: "Begin a reading", caption: "HEXAGRAM / FORM / CHANGE", imageAlt: "King Wen arranging yarrow stalks beneath a divine cosmos as the Yi connects across dimensions" },
    features: { label: "Core features", methodsTitle: "Three verified methods", methodsBody: "Choose three numbers, three coins, or secure random casting—each follows fixed, reviewable rules.", interpretationTitle: "AI-powered interpretation guided by Takashima’s book", interpretationBody: "Reviewed material from Takashima Ekidan grounds each optional AI interpretation.", chatTitle: "Powerful follow-up chat", chatBody: "Keep the full reading in context as you ask questions and explore what it means." },
    cast: { title: "Your question", questionHint: "Write a bounded question you can reflect on (280 characters max)", noQuestion: "I do not have a specific question", continue: "Choose a casting method", methodTitle: "Choose a method", number: "Three numbers", numberBody: "Enter upper and lower trigrams and one changing line.", coin: "Three coins", coinBody: "Record six throws of three coins, beginning at the bottom.", random: "Secure random", randomBody: "Generated with browser cryptography, then reviewed before submission.", upper: "Upper trigram (1-8)", lower: "Lower trigram (1-8)", changing: "Changing line (1-6)", heads: "Heads", tails: "Tails", line: "Line {{n}}", bottom: "First / bottom", top: "Sixth / top", generate: "Generate secure cast", regenerate: "Generate again", review: "Review the lines", reviewTitle: "Review before submitting", bottomUp: "Lines are shown bottom to top. Changing lines are orange.", yin: "Yin", yang: "Yang", moving: "Changing", still: "Still", back: "Edit", confirm: "Confirm and choose contribution", invalid: "Complete and check all casting inputs.", resume: "Resume current cast", exit: "Exit casting", stepCount: "Step {{current}} of {{total}}", progressLabel: "Casting progress", stepChanged: "Now on {{step}}", generated: "Secure random cast generated" },
    trigrams: { 1: "Qian · Heaven", 2: "Dui · Lake", 3: "Li · Fire", 4: "Zhen · Thunder", 5: "Xun · Wind", 6: "Kan · Water", 7: "Gen · Mountain", 8: "Kun · Earth" },
    methodGuide: {
      title: "How does this method work?",
      number: { body: "The first two numbers select the trigrams; the third selects the changing line.", point1: "Enter 1–8 for the upper and lower trigrams. The matching trigram appears below each field.", point2: "Enter 1–6 for the changing line, counted from bottom to top. This method always has exactly one changing line." },
      coin: { body: "Each of the six throws creates one line, beginning at the bottom.", point1: "Set each throw’s three coins to Heads or Tails. Heads count as 3 and tails as 2.", point2: "A total of 6 is changing yin, 7 stable yang, 8 stable yin, and 9 changing yang.", point3: "A cast may have no changing lines or several changing lines." },
      random: { body: "Your browser securely generates all six line values at once, then lets you review them.", point1: "Broken lines are yin and solid lines are yang. White lines are stable; orange lines are changing.", point2: "A cast may have no changing lines or several. Generate again if you want a new cast.", point3: "The commitment code below is a cryptographic digest of the random data. It records this generation without revealing the original random data." },
    },
    contribution: { title: "Voluntary contribution", body: "This supports the digital service and is not a charitable donation. HK$0 completes immediately. Positive amounts use Stripe-hosted Checkout; only a verified webhook reveals the result.", custom: "Custom whole HK$1-888", proceed: "Complete and view result", checkout: "Continue to Stripe Checkout", pending: "Waiting for payment confirmation", cancelled: "Checkout was cancelled. You can choose again.", unavailable: "Positive contributions will return after Stripe setup; the complete HK$0 reading remains available." },
    specialLine: { nine: "All six yang lines changing", six: "All six yin lines changing" },
    result: { waiting: "Your result is being prepared", waitingBody: "Only a verified Stripe notification confirms payment. This page updates automatically.", primary: "Primary", relating: "Relating", kingWenOrder: "King Wen", movingLines: "Changing lines", none: "No changing lines", facts: "Reproducible facts", sourcePending: "Source catalog under review", sourceBody: "Only facts independent of interpretation texts are shown. Source interpretation and source-grounded AI stay off until rights and trilingual review are complete.", sourceReviewed: "Reviewed source catalog", sourceReviewedBody: "This reading carries fixed excerpts with provenance, rights status, and trilingual review. They are sent to AI only with your separate consent.", reflection: "AI reflection", reflectionQuestions: "Questions to carry forward", reflectionCautions: "Reading notes", askReflection: "Choose whether to add AI reflection", archive: "Save this reading", archived: "Saved", again: "Cast again", chat: "Discuss this reading", share: "Create anonymous share" },
    consent: { title: "You choose what is sent", body: "AI is optional. Every operation needs explicit consent; high-stakes questions never go to the model.", agree: "I consent to sending the selected data to DeepSeek for a reflection", facts: "I consent to sending this reading’s facts to DeepSeek", question: "Include my original question", sources: "Include reviewed source excerpts", submit: "Create reflection", decline: "Skip AI", fallback: "AI was not used; the deterministic result remains complete." },
    auth: { eyebrow: "Archive / Notes / Chat", or: "or", title: "Your reading space", signIn: "Sign in", signUp: "Create account", name: "Name", email: "Email", password: "Password (10+ characters)", confirmPassword: "Confirm new password", submit: "Continue", google: "Continue with Google", microsoft: "Continue with Microsoft", verify: "If the account exists, check your email and follow the link to continue.", verified: "Email verified. You can now sign in.", invalidLink: "This link is invalid or expired. Request a new one.", forgot: "Forgot password?", reset: "Send reset link", newPasswordTitle: "Set a new password", newPasswordBody: "Enter a new password of at least 10 characters.", setPassword: "Update password", resetDone: "Password updated. Sign in with your new password.", signOut: "Sign out", needAccount: "Saving, notes, search, and chat require an account." },
    history: { eyebrow: "Personal archive", saved: "Saved reading", searchLabel: "Search reading history", title: "Reading history", empty: "No saved readings yet.", emptyTitle: "Begin with a reading", noMatches: "No readings match that search.", search: "Search questions, readings, reflections, and notes", notes: "Notes", addNote: "Add a note", saveNote: "Save note", noteSaved: "Note saved", delete: "Delete", deleteReading: "Delete this reading", deleteConfirm: "Permanently delete this reading?", open: "Open" },
    chat: { eyebrow: "Persistent / resumable", title: "Reading conversation", intro: "The conversation keeps the reading context from the moment it starts. Up to 50 turns per day.", placeholder: "Write what you want to untangle…", send: "Send", reconnecting: "Reconnecting…", connected: "Connected", statusLabel: "Connection status", empty: "Begin with the part you most want to untangle.", you: "You", delete: "Delete conversation", deleteConfirm: "Permanently delete this conversation?" },
    share: { title: "Anonymous sharing", anonymous: "Anonymous / Seven days", body: "The link contains only facts and the reflection you choose. No identity, question, notes, or chat. It expires in seven days.", includeReflection: "Include AI reflection", create: "Create seven-day link", copy: "Copy link", native: "Share", image: "Download long image and QR", revoked: "Share revoked", expired: "This share is missing, revoked, or expired", url: "Share link", imageTagline: "A private reflection, shared anonymously", expires: "Expires {{date}}" },
    settings: { eyebrow: "Personalize", title: "Settings", locale: "Language", font: "Text size", theme: "Appearance", small: "Small", medium: "Medium", large: "Large", light: "Light", dark: "Dark", system: "System", save: "Save settings", export: "Export my data", delete: "Delete account", deleteBody: "A confirmation email will be sent. After confirmation, the account and saved data cannot be recovered." },
    help: { eyebrow: "About / Method / Privacy", title: "Use the reading as a mirror", body1: "Yi generates six lines from your chosen method, then uses a fixed King Wen mapping to identify the primary and relating hexagrams. The same inputs always produce the same facts.", body2: "It is not prediction, diagnosis, investment, or legal advice. Use it to frame a question, notice assumptions, and design one reversible next step.", methods: "All three methods preserve bottom-to-top line order and require review before submission.", privacy: "Shares are always anonymous; AI consent and data scope are chosen each time.", takashima: { eyebrow: "People / Yi tradition", title: "Kaemon Takashima", body: "Kaemon Takashima (1832–1914), also known by the art name Donshō, was a Yokohama businessman and diviner active from the late Edo period into the Meiji era. Born in Edo’s Sanjikkenbori district, he was named Seizaburō in childhood and later took the names Kahei and Kaemon.", source: "Read the Japanese Wikipedia article" } },
    contact: { eyebrow: "Support / Feedback", title: "Contact us", subject: "Subject", message: "Message", send: "Send", received: "Received. We will reply in order." },
    turnstile: { label: "Bot verification", error: "The security check could not complete. Refresh the page, or try another browser without a VPN or proxy." },
    admin: { eyebrow: "Restricted / Content-redacted", title: "Operations console", summary: "Summary", users: "Accounts", readings: "Reading metadata", contributions: "Contributions & payments", ai: "AI usage", config: "Limits", noContent: "Normal operations views never display question, note, or chat content." },
    ops: { id: "ID", email: "Email", role: "Role", status: "Status", activate: "Activate", suspend: "Suspend", dashboard: "Dashboard", aiEnabled: "Global AI enabled", tokens: "Daily token budget", spend: "Daily spend budget (USD micros)", concurrency: "Maximum provider concurrency", save: "Save limits", saving: "Saving…" },
    common: { loading: "Loading…", loadingTitle: "Preparing the page", error: "That did not complete. Please try again.", retry: "Retry", close: "Close", save: "Save", cancel: "Cancel", optional: "Optional", copyDone: "Copied", back: "Back" },
  } },
} as const;

const storedLocale = localStorage.getItem("yi-locale");
const initialLocale: AppLocale = supportedLocales.includes(storedLocale as AppLocale) ? storedLocale as AppLocale : "zh-HK";

void i18n.use(initReactI18next).init({
  resources,
  lng: initialLocale,
  fallbackLng: "zh-HK",
  interpolation: { escapeValue: false },
});

document.documentElement.lang = initialLocale;

export function chooseLocale(locale: AppLocale) {
  localStorage.setItem("yi-locale", locale);
  document.documentElement.lang = locale;
  return i18n.changeLanguage(locale);
}

export default i18n;
